Update index.js
I have still been getting:

```
/path/to/node_modules/koa-sass/index.js:2
var mw = require('node-sass-middleware').middleware(options);
                            ^
TypeError: undefined is not a function
```

Having checked the node-sass-middleware docs the `middleware` function seems depreciated.